// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as PgTypes } from '@prisma-next/adapter-postgres/codec-types';
import type { JsonValue } from '@prisma-next/adapter-postgres/codec-types';
import type { Char } from '@prisma-next/adapter-postgres/codec-types';
import type { Varchar } from '@prisma-next/adapter-postgres/codec-types';
import type { Numeric } from '@prisma-next/adapter-postgres/codec-types';
import type { Bit } from '@prisma-next/adapter-postgres/codec-types';
import type { VarBit } from '@prisma-next/adapter-postgres/codec-types';
import type { Timestamp } from '@prisma-next/adapter-postgres/codec-types';
import type { Timestamptz } from '@prisma-next/adapter-postgres/codec-types';
import type { Time } from '@prisma-next/adapter-postgres/codec-types';
import type { Timetz } from '@prisma-next/adapter-postgres/codec-types';
import type { Interval } from '@prisma-next/adapter-postgres/codec-types';

import type {
  ExecutionHashBase,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';
import type {
  SqlContract,
  SqlStorage,
  SqlMappings,
  ModelDefinition,
} from '@prisma-next/sql-contract/types';

export type StorageHash =
  StorageHashBase<'sha256:ff0778a374cf5bfab191df9ab0cd6520f3facb845e4950a30b753a1c0d635d31'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'sha256:f8f8f7f23ce43cd1b7344e9c97651617112e7d216338d43f071a445b1fca8627'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type OperationTypes = Record<string, never>;
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId] extends { readonly output: infer O }
    ? O extends Date | bigint
      ? O
      : Encoded
    : Encoded
  : Encoded;

export type Contract = SqlContract<
  {
    readonly tables: {
      readonly box: {
        columns: {
          readonly id: {
            readonly nativeType: 'int4';
            readonly codecId: 'pg/int4@1';
            readonly nullable: false;
            readonly default: { readonly kind: 'function'; readonly expression: 'autoincrement()' };
          };
          readonly color: {
            readonly nativeType: 'text';
            readonly codecId: 'pg/text@1';
            readonly nullable: false;
          };
        };
        primaryKey: { readonly columns: readonly ['id'] };
        uniques: readonly [];
        indexes: readonly [];
        foreignKeys: readonly [];
      };
    };
    readonly types: Record<string, never>;
  },
  {
    readonly Box: {
      storage: { readonly table: 'box' };
      fields: {
        readonly id: CodecTypes['pg/int4@1']['output'];
        readonly color: CodecTypes['pg/text@1']['output'];
      };
    };
  },
  Record<string, never>,
  {
    modelToTable: { readonly Box: 'box' };
    tableToModel: { readonly box: 'Box' };
    fieldToColumn: { readonly Box: { readonly id: 'id'; readonly color: 'color' } };
    columnToField: { readonly box: { readonly id: 'id'; readonly color: 'color' } };
    codecTypes: PgTypes;
    operationTypes: Record<string, never>;
  },
  StorageHash,
  ExecutionHash,
  ProfileHash
>;

export type Tables = Contract['storage']['tables'];
export type Models = Contract['models'];
export type Relations = Contract['relations'];
